-- PostgreSQL

DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (

	id SERIAL PRIMARY KEY,
	username VARCHAR(25) NOT NULL,
	password_hash VARCHAR(60) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	token VARCHAR(20),
	token_expires TIMESTAMP
);

CREATE TABLE friends (

	id1 INTEGER NOT NULL REFERENCES users(id),
	id2 INTEGER NOT NULL REFERENCES users(id),
	since TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id1, id2)
);